USE pro2;
DROP FUNCTION IF EXISTS validarLetras;
DELIMITER $$
CREATE FUNCTION validarLetras(str VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (str REGEXP '^[a-zA-Zaáéíóú ]*$',true,false);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarNumeros;
DELIMITER $$
CREATE FUNCTION validarNumeros(num VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (num REGEXP '^[0-9]*$',true,false);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarDecimales;
DELIMITER $$
CREATE FUNCTION validarDecimales(num VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (num REGEXP '^[0-9]*(\.[0-9]*)?$',true,false);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarCiclo;
DELIMITER $$
CREATE FUNCTION validarCiclo(ciclo VARCHAR(2))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF 
(BINARY ciclo = '1S' 
OR BINARY ciclo= '2S' 
OR BINARY ciclo= 'VD' 
OR BINARY ciclo= 'VJ', TRUE, FALSE);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarSeccion
DELIMITER $$
CREATE FUNCTION validarSeccion(num VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (num REGEXP '^[A-Z]$',true,false);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarEmail;
DELIMITER $$
CREATE FUNCTION validarEmail(email VARCHAR(60))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF 
(email REGEXP '^[a-zA-Z0-9]+@[a-zA-Z]+(\.[a-zA-Z]+)+$',true,false);
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS validarHorario;
DELIMITER $$
CREATE FUNCTION validarHorario(rango VARCHAR(20))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF 
(rango REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]-(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$', true, false);
END $$
DELIMITER ;


